Make file_io.py compatible with Python3.8
Summary:
Python 3.8 doesn't support the syntactic sugar for union types, e.g., `bytes | str`. Here's the error message:
```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/mack/scratch/anaconda3/envs/py3.8/lib/python3.8/site-packages/airstore/client/airstore_tabular.py", line 68, in <module>
    from iopath.common.file_io import PathManager, TabularIO
  File "/home/mack/scratch/anaconda3/envs/py3.8/lib/python3.8/site-packages/iopath/common/__init__.py", line 5, in <module>
    from iopath.common.file_io import file_lock, get_cache_dir, LazyPath, PathManager
  File "/home/mack/scratch/anaconda3/envs/py3.8/lib/python3.8/site-packages/iopath/common/file_io.py", line 562, in <module>
    class NativeAsyncReader(IOBase):
  File "/home/mack/scratch/anaconda3/envs/py3.8/lib/python3.8/site-packages/iopath/common/file_io.py", line 579, in NativeAsyncReader
    async def read(self) -> bytes | str:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

This diff changes the one offending type hint in `file_io.py` to make it compatible with Python 3.8 again.

Reviewed By: ASchneidman

Differential Revision: D69014376

fbshipit-source-id: f94ee1d58a2f87993fedb45b5b4d5761611044c5